package com.bairei.javafxapp.models;

public enum  Genre {
    ROCK, METAL, POP, JAZZ, BLUES, PROGRESSIVE, ALTERNATIVE, PUNK, HARDCORE, GRINDCORE, THRASH_METAL,
    RAP, FUNK, SLUDGE, GROOVE, DEATH_METAL, BLACK_METAL, MATH, MATHCORE
}
